const MenuPage = () => {
    return(
        <>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
            <div>메뉴페이지</div>
        </>
    )
}

export default MenuPage